#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.3.0a4_7368acd360f4"
#define UNITY_VERSION_FULL_NICE "2019.3.0a4 (7368acd360f4)"
#define UNITY_VERSION_BLD 7563436
#define UNITY_VERSION_DATE 1558464041
#define UNITY_VERSION_WIN "2019.3.0.7563436"
#define UNITY_VERSION_BRANCH "trunk"
